log_dir: ${name}/
resume:

metrics:
  - cls: model.metric.accuracy
  - cls: model.metric.top_k_acc

defaults:
  - status: train
  - structure: mnist_lenet
  - hparams: lenet_baseline

  - hydra/job_logging : custom
  - hydra/run/dir: job_timestamp
