log_dir: ${name}/
resume:

metrics:
  - _target_: srcs.model.metric.accuracy
  - _target_: srcs.model.metric.top_k_acc

defaults:
  - dataset: mnist_train

  - status: train
  - structure: mnist_lenet
  - hparams: lenet_baseline

  - hydra/job_logging : custom
  - hydra/run/dir: job_timestamp
