name: MnistLeNet
arch:
  class: model.model.MnistModel
  params:
    num_classes: 10
data_loader:
  class: data_loader.data_loaders.MnistDataLoader
  params:
    data_dir: /data/private/pytorch-template/data
    batch_size: ${batch_size}
    shuffle: true
    validation_split: 0.1
    num_workers: ${n_cpu}
loss:
  class: torch.nn.NLLLoss
optimizer:
  class: torch.optim.Adam
  params:
    lr: ${learning_rate}
    weight_decay: ${weight_decay}
    amsgrad: true
lr_scheduler:
  class: torch.optim.lr_scheduler.StepLR
  params:
    step_size: ${scheduler_step_size}
    gamma: ${scheduler_gamma}
