# @package _global_
name: MnistLeNet
arch:
  cls: srcs.model.model.MnistModel
  params:
    num_classes: 10
data_loader:
  cls: srcs.data_loader.data_loaders.get_data_loaders
  params:
    data_dir: /data/private/pytorch-template/data
    batch_size: ${batch_size}
    shuffle: true
    validation_split: 0.1
    num_workers: ${n_cpu}
loss:
  cls: srcs.model.loss.nll_loss
optimizer:
  cls: torch.optim.Adam
  params:
    lr: ${learning_rate}
    weight_decay: ${weight_decay}
    amsgrad: true
lr_scheduler:
  cls: torch.optim.lr_scheduler.StepLR
  params:
    step_size: ${scheduler_step_size}
    gamma: ${scheduler_gamma}
